### ISSUE TITLE
NLTK punkt download failure

### ISSUE THREAD

**Issue by matlecam** [dataiku/dss-plugin-nlp-summarization#1]
Hi,

Thanks for the work on this plugin!
I am currently facing issues running it in an isolated environment without Internet access.
I did install all the NLTK dependencies locally and set the NLTK_DATA env variable accordingly and can use the nltk module from Python without issue.
The plugin does explicitly try to download the **punkt** package though, which obviously fails in my case.

https://github.com/dataiku/dss-plugin-nlp-summarization/blob/894b6341d8794e78e844b97512d3de5486818eaa/custom-recipes/text-summarization-compute/recipe.py#L16

Do you think we could make the download optional?

**Comment by alexcombessie** [comment]
Hi,

Thanks for your feedback. We plan to address this issue of NLTK dependency in offline user-isolated environments in a future plugin release.

In the meantime, let me investigate if a quick fix is possible.

Best regards,

Alex

**Comment by Muennighoff** [comment]
This issue is resolved in the forthcoming 1.3.0 release 😇
